// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Afivve",
    "email": "user@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
// Get all users
GET http://localhost:5000/users

###
// Get single user
GET http://localhost:5000/users/80a63767-0761-43eb-ac9f-426987d907ec

###
// Update User
PATCH http://localhost:5000/users/80a63767-0761-43eb-ac9f-426987d907ec
Content-Type: application/json

{
    "name": "Afivvee",
    "email": "user@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
// Delete User
DELETE http://localhost:5000/users/80a63767-0761-43eb-ac9f-426987d907ec

###
// Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456"
}

###
// Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout

###
// Get All Product
GET http://localhost:5000/products

###
// Get Single Product
GET http://localhost:5000/products/484ebf92-e6e3-4a8d-b7ef-b51641730a50

###
// Create Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Produk 6",
    "price": "10000"
}

###
// Update Product
PATCH http://localhost:5000/products/484ebf92-e6e3-4a8d-b7ef-b51641730a50
Content-Type: application/json

{
    "name": "Produk New Update",
    "price": "10000"
}

###
// Delete Product
DELETE http://localhost:5000/products/484ebf92-e6e3-4a8d-b7ef-b51641730a50